/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prescribing;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Jai Deep
 */
public class prescription extends javax.swing.JFrame {

    /**
     * Creates new form prescription
     */
    
    public prescription() {
        initComponents();
       AutoCompleteDecorator.decorate(medicine);
     
       currentdate();
       
    }
    
    void currentdate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yy ");  
   LocalDateTime now = LocalDateTime.now();  
   date.setText(dtf.format(now));
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiResolutionImageSupport1 = new com.formdev.flatlaf.util.MultiResolutionImageSupport();
        flatComboBoxUI1 = new com.formdev.flatlaf.ui.FlatComboBoxUI();
        flatPasswordFieldUI1 = new com.formdev.flatlaf.ui.FlatPasswordFieldUI();
        flatTextFieldUI1 = new com.formdev.flatlaf.ui.FlatTextFieldUI();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        name = new javax.swing.JTextField();
        Type = new javax.swing.JComboBox<>();
        medicine = new javax.swing.JComboBox<>();
        dose = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Delete = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        print = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        dosage = new javax.swing.JComboBox<>();
        date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        days = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "AL-HADEED DENTAL CLINIC", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 0, 36))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Medicine", "Dose", "Dosage", "Days"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Area.setColumns(20);
        Area.setRows(5);
        Area.setBorder(javax.swing.BorderFactory.createTitledBorder("Print Preview"));
        Area.setFocusable(false);
        jScrollPane2.setViewportView(Area);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        Type.setBackground(new java.awt.Color(255, 255, 255));
        Type.setEditable(true);
        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Cap", "Cream", "Inj", "Tab", "Syrup", "Gel", "M/Wash", "T/Paste " }));
        Type.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        Type.setOpaque(false);

        medicine.setBackground(new java.awt.Color(255, 255, 255));
        medicine.setEditable(true);
        medicine.setForeground(new java.awt.Color(0, 0, 0));
        medicine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alp  ", "Augmentin  ", "Augmentin Ds  ", "Amoxiclave  ", "Amclav  ", "Amoxil  ", "Amoxicillin  ", "Abc  ", "Ansaid  ", "Apronax  ", "Brufen  ", "Brufen Ds  ", "Brexin  ", "Bonjela  ", "Caflam  ", "Clinica  ", "Cac 1000   ", "Conzyme  ", "Chymoral Forte  ", "Calamox  ", "Cycin  ", "Dalacin C  ", "Duricef   ", "Duragesic   ", "Dicloran  ", "Dicloran  Disperlet  ", "Dyclo  ", "Danzen  ", "Danzen Ds  ", "Daktarin  ", "Enziclor  ", "Entamizole  ", "Flagyl  ", "Froben  ", "Fasted Plus  ", "Forhens  ", "Feldene   ", "Folic Acid   ", "Hisalz  ", "Hiparadent  ", "Klint  ", "Klaricid   ", "Klaricid Ds   ", "Kenalog  ", "Leflox   ", "Lycn   ", "Lincocin  ", "Listrine  ", "Mixel  ", "Mixel Ds  ", "Metrozine  ", "Movex  ", "Modact Ir  ", "Macleans  ", "Maxit  ", "Nims  ", "Nice  ", "Novidat  ", "Nexium  ", "Niflam  ", "Napa   ", "Oral-B  ", "Ospamox  ", "Panadol  ", "Ponstan  ", "Ponstan Forte   ", "Prodent  ", "Protect  ", "Protect G  ", "P-Cam  ", "Phlogin  ", "Qufen Sr  ", "Qufen  ", "Risek  ", "Remethan   ", "Risek Insta   ", "Roxvita   ", "Ruling   ", "Somogel  ", "Sensodine  ", "Sensodine R/Action  ", "Surbex Z   ", "Synflex  ", "Signal  ", "Synalgo  ", "Tormex Ir  ", "Tramal  ", "Tramal Sr  ", "Tegral   ", "Terial   ", "Toxidal   ", "Tercica  ", "Unix  ", "Velosef  ", "Vericef  ", "Voren  ", "Voltral  ", "Vibramycin   ", "Xanax   ", "Xianbial   " }));
        medicine.setSelectedIndex(-1);
        medicine.setAutoscrolls(true);
        medicine.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medicines", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        medicine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        medicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicineActionPerformed(evt);
            }
        });

        dose.setBackground(new java.awt.Color(255, 255, 255));
        dose.setEditable(true);
        dose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "10mg", "15mg", "20mg", "50mg", "75mg", "100mg", "125mg", "150mg", "200mg", "250mg", "300mg", "375mg", "400mg", "500mg", "625mg", "1gm" }));
        dose.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dose", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        dose.setOpaque(false);
        dose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doseActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Remarks/Next Visit"));
        jScrollPane3.setViewportView(jTextArea2);

        Delete.setBackground(new java.awt.Color(255, 51, 51));
        Delete.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("REMOVE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(0, 204, 0));
        Add.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("INSERT");
        Add.setNextFocusableComponent(medicine);
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(153, 153, 153));
        print.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        prev.setBackground(new java.awt.Color(153, 153, 153));
        prev.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        prev.setForeground(new java.awt.Color(255, 255, 255));
        prev.setText("PREVIEW");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });

        dosage.setBackground(new java.awt.Color(255, 255, 255));
        dosage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0+0+1", "0+1+0", "0+1+1", "1+0+1", "1+1+1" }));
        dosage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dosage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 2, 12))); // NOI18N
        dosage.setNextFocusableComponent(days);
        dosage.setOpaque(false);
        dosage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosageActionPerformed(evt);
            }
        });

        date.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        date.setText("auto_date");

        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel2.setText("DATE:");

        days.setBorder(javax.swing.BorderFactory.createTitledBorder("Duration"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(prev, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medicine, 0, 183, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Type, 0, 114, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dose, 0, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dosage, 0, 102, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(days)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(date)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medicine, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dose, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dosage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(days, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        days.getAccessibleContext().setAccessibleName("days");

        jLabel1.setFont(new java.awt.Font("Segoe Script", 3, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void doseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doseActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void medicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicineActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_medicineActionPerformed

    private void dosageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dosageActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
       
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{Type.getSelectedItem().toString(),medicine.getSelectedItem().toString(),dose.getSelectedItem().toString(),dosage.getSelectedItem().toString(),days.getText()});
        medicine.setSelectedIndex(-1);
        Type.setSelectedIndex(0);
        dose.setSelectedIndex(0);
        dosage.setSelectedIndex(0);
        days.setText("");
       
    }//GEN-LAST:event_AddActionPerformed
    
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"No Data To Delete", "Note",JOptionPane.OK_OPTION);

            }else{
                JOptionPane.showMessageDialog(null,"Select A Row To Delete", "Note",JOptionPane.OK_OPTION);
            }

        }else{
            model.removeRow(jTable1.getSelectedRow());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
//        if(jTable1.getRowCount()==0){
//            JOptionPane.showMessageDialog(null,"No Data In Table", "Note",JOptionPane.OK_OPTION);
//        }else{
        Area.setText(Area.getText()+"\n\n\n\n\n\n\t\t\t\t                 "+date.getText()+"\n");
        Area.setText(Area.getText()+"\n\n\t\tPatient Name: "+name.getText());
        
      
        Area.setText(Area.getText()+"\n"+"\t     "+"=================================");
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
     
        for(int i=0; i<jTable1.getRowCount();i++){
            String type=jTable1.getValueAt(i,0).toString();
            String medicine=jTable1.getValueAt(i,1).toString();
            String dose=jTable1.getValueAt(i,2).toString();
            String dosage=jTable1.getValueAt(i,3).toString();
            String day=jTable1.getValueAt(i,4).toString();
            Area.setText(Area.getText()+"\n\t     "+type+"\t"+medicine+"  "+dose+"\t\n\t\t"+dosage+"\t"+day+" Days");
        }
        Area.setFont(Area.getFont().deriveFont(Font.BOLD, Area.getFont().getSize()));
        Area.setText(Area.getText()+"\n\t     =================================");
        Area.setText(Area.getText()+"\n\t     "+"Remarks/Next Visit:"+"\n\t     "+jTextArea2.getText()+"\n");
        Area.setText(Area.getText()+"\n\n\n\n\n\t\t"+"Computer Generated Print-out.\n\t\t    No Signature Required");
        
    }//GEN-LAST:event_prevActionPerformed
    
    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        if("".equals(Area.getText())){
            JOptionPane.showMessageDialog(null, "No Data In Field", "Note", HEIGHT);
        }else{
         try{
            Area.print();
            Area.setText("");
            jTextArea2.setText("");
            name.setText("");
            
            DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            int rowCount = model.getRowCount();
//Remove rows one by one from the end of the table
for (int i = rowCount - 1; i >= 0; i--) {
    model.removeRow(i);
}
        }
        catch(PrinterException ex){
            Logger.getLogger(prescription.class.getName()).log(Level.SEVERE,null, ex);
        }
         }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
       try{
          UIManager.setLookAndFeel(new FlatIntelliJLaf());
         
          
      
      }catch(Exception e){
          e.printStackTrace();
      }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new prescription().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextArea Area;
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JLabel date;
    private javax.swing.JTextField days;
    private javax.swing.JComboBox<String> dosage;
    private javax.swing.JComboBox<String> dose;
    private com.formdev.flatlaf.ui.FlatComboBoxUI flatComboBoxUI1;
    private com.formdev.flatlaf.ui.FlatPasswordFieldUI flatPasswordFieldUI1;
    private com.formdev.flatlaf.ui.FlatTextFieldUI flatTextFieldUI1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> medicine;
    private com.formdev.flatlaf.util.MultiResolutionImageSupport multiResolutionImageSupport1;
    private javax.swing.JTextField name;
    private javax.swing.JButton prev;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
